import {
	attribute,
	autoGeneratedHashKey,
	rangeKey,
	table,
} from "@aws/dynamodb-data-mapper-annotations";
import { LogLevel } from "../enums/log-level.enum";

@table("logs")
export class LogEntity {
	@autoGeneratedHashKey()
	id: number;

	@attribute()
	message: string;

	@rangeKey({defaultProvider: () => new Date()})
    timestamp: Date;

	@attribute({ type: "String" })
	level?: LogLevel;

}
